FROM public.ecr.aws/lambda/python:3.8

ARG LAMBDA_TASK_ROOT="./app/handler.py"

# Copy function code
COPY ${LAMBDA_TASK_ROOT} app.py 

# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]